remove CI until I figure a better way in general

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -8,31 +8,31 @@ on:
       - '.github/workflows/**'
 
 jobs:
-  CI:
-    runs-on: docker-test
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+  # CI:
+  #   runs-on: docker-test
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
 
-      - name: test service
-        run: |
-          cd docker
-          docker compose up -d
+  #     - name: test service
+  #       run: |
+  #         cd docker
+  #         docker compose up -d
 
-          echo "Sleeping for 15 seconds"
-          sleep 15
+  #         echo "Sleeping for 15 seconds"
+  #         sleep 15
 
-          if docker logs nhvilhelmsen.com | grep -i "error"; then
-            echo "Error found in logs"
-            docker logs nhvilhelmsen.com | grep "error"
-            exit 1
-          else
-            echo "No errors found in logs"
-          fi
+  #         if docker logs nhvilhelmsen.com | grep -i "error"; then
+  #           echo "Error found in logs"
+  #           docker logs nhvilhelmsen.com | grep "error"
+  #           exit 1
+  #         else
+  #           echo "No errors found in logs"
+  #         fi
 
   CD:
-    needs: CI
-    runs-on: docker
+    # needs: CI
+    runs-on: docker-mini
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
